production:
  adapter: postgresql
  encoding: unicode
  database: ensemble_production
  pool: 5
  username: <%= ENV['ENSEMBLE_DB_USER'] %>
  password: <%= ENV['ENSEMBLE_DB_PASSWORD'] %>
  host: localhost